### ISSUE TITLE
As an organziational applicant, I would like to submit my application

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-middlelayer-api#68]
# Notes
Currently not submitting the Organizational responses correctly.
Convert for lower case

# Acceptance Criteria
- [ ] When I submit an nc application as an organziation, I should be able to get a control number
- [ ] When I submit an temp outfitter and guide app, as an org, I should be able to get a control number.

## Tasks
- [X] Send an orgType key
- [  ] Make it upercase.

**Comment by lauraGgit** [comment]
@hannahkane can you say was this tagged as `Cedar` because it was in progress? If so we might want to verify where were at with this because I'm not sure we have really been working on this this sprint.

**Comment by hannahkane** [comment]
Yeah, sorry, it's just because it's in the Review column. I'll remove the milestone, but should it also move to the backlog?

**Comment by lauraGgit** [comment]
Ok, this hasn't been validated against SUDS yet, but it does look like its in the codebase. Closing for now.
