### ISSUE TITLE
As an outfitter/guide, I can upload a file to show where my trips will go in addition to using the text box.

### ISSUE THREAD

**Issue by rrefoy** [18F/fs-middlelayer-api#79]
## Notes
Outfitters are required to submit a PDF or JPG map, but the application only allows location descriptions in text.

Severity: High - prevents accurate form submissions
Difficulty of remediation: Medium - would require adding a field in the middle layer and intake module

Acceptance tests:

- [ ] User sees information letting them know they can submit pdf or jpg files
- [ ] User can submit pdf or jpg file
- [ ] User cannot submit any other file type

## Tasks
- [ ] update help text for location text box to reflect additional information including why a map is 
       required 
- [ ] Add an upload component for an optional map
- [ ] Develop help text for map upload
- [ ] Add to platform database
- [ ] Add upload component to platform server
- [ ] Update the middle layer database
- [ ] Update the middle layer schema
- [ ] Allow for .pdf, .jpg, .png files to be uploaded
- [ ] Add test for frontend
- [ ]  Add test for platform server

**Comment by lauraGgit** [comment]
Part of [FFP #153](https://github.com/18F/fs-permit-platform/issues/153)

**Comment by lauraGgit** [comment]
![image](https://user-images.githubusercontent.com/5840989/41308884-1ddf79ea-6e4b-11e8-9e6e-da6e05a3be75.png)
then change over middlelayer schema/ intake s3/middlelayer s3

**Comment by hannahkane** [comment]
@msadakFS - do you know if SUAs will likely need to submit multiple files?

**Comment by msadakFS** [comment]
@hannahkane Being able to upload a map would be a nice feature. For instance, a whitewater rafting guide may already have a map on a brochure that they could upload. I believe an attached map is a requirement and gets attached as an appendix on a traditional application. This would be a question for the local SME as I am not sure of the exact requirement.

**Comment by hannahkane** [comment]
@msadakFS - I think we have confirmed that applicants need to submit maps. What I was wondering was whether they can meet that requirement with a single file upload, or if they might need to upload multiple files/maps. I believe the current file upload UI we have only allows for a single file. I was just wondering if that meets the user need.

**Comment by lauraGgit** [comment]
I think we may want to have both - as the actual form does require some sort of description on this. and then we can have an optional file upload for the map ... Optional in this case, means not there with the original submission.

**Comment by hannahkane** [comment]
@lauraGgit - not sure I follow. Can you explain "not there with the original submission" further?

**Comment by lauraGgit** [comment]
@hannahkane all the optional files eventually have to be submitted, they might just not be ready at the time the applicant initially submits their application.

**Comment by hannahkane** [comment]
Would an SUA mark that application as "On Hold" then? Do we want to consider creating a "Save draft" workflow for applicants who want to complete the application over several sessions? 

I realize this is in the current sprint, but it might be worth discussing at today's backlog grooming meeting. cc @msadakFS
